import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./login.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

const LoginLayout = ({
  children
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return <div className={inter.className}>{children}</div>;
};

export default LoginLayout;
